dog_breeds = [
    "Airedale Terrier", "Akita", "Alaskan Klee Kai", "Alaskan Malamute", 
    "American Eskimo Dog", "American Pit Bull Terrier", "American Water Spaniel", 
    "Anatolian Shepherd Dog", "Australian Cattle Dog", "Australian Shepherd", 
    "Australian Terrier", "Basset Hound", "Basenji", "Beagle", "Belgian Malinois", 
    "Belgian Tervuren", "Bichon Frise", "Black Russian Terrier", "Bloodhound", 
    "Blue Lacy Dog", "Bolognese", "Borzoi", "Boston Terrier", "Border Collie", 
    "Border Terrier", "Boxer", "Boykin Spaniel", "Brussels Griffon", "Bull Terrier", 
    "Cairn Terrier", "Cane Corso", "Cardigan Welsh Corgi", "Cavalier King Charles Spaniel", 
    "Chesapeake Bay Retriever", "Chinese Crested", "Chinese Shar-Pei", "Clumber Spaniel", 
    "Collie", "Cocker Spaniel", "Cocker Spaniel", "Curly-Coated Retriever", "Dalmatian", 
    "Dandie Dinmont Terrier", "Doberman Pinscher", "English Cocker Spaniel", 
    "English Setter", "English Springer Spaniel", "Field Spaniel", "Finnish Lapphund", 
    "Finnish Spitz", "French Bulldog", "German Pinscher", "German Shepherd", 
    "German Shorthaired Pointer", "Giant Schnauzer", "Gordon Setter", "Golden Doodle", 
    "Golden Retriever", "Grand Basset Griffon Vendeen", "Great Dane", "Great Pyrenees", 
    "Greyhound", "Havanese", "Irish Setter", "Irish Wolfhound", "Italian Greyhound", 
    "Italian Spinone", "Jack Russell Terrier", "Japanese Chin", "Kerry Blue Terrier", 
    "Keeshond", "King Charles Spaniel", "Komondor", "Labradoodle", "Labrador Retriever", 
    "Lagotto Romagnolo", "Leonberger", "Lhasa Apso", "Maltese", "Maltipoo", "Miniature Pinscher", 
    "Miniature Schnauzer", "Mudi", "Newfypoo", "Newfoundland", "Norwegian Elkhound", 
    "Old English Sheepdog", "Otterhound", "Papillon", "Pekingese", "Pharaoh Hound", 
    "Pit Bull Terrier", "Plott Hound", "Portuguese Water Dog", "Poodle", "Pug", "Rat Terrier", 
    "Redbone Coonhound", "Rhodesian Ridgeback", "Rottweiler", "Saint Bernard", 
    "Samoyed", "Schipperke", "Scottish Terrier", "Shiba Inu", "Shih Tzu", "Silky Terrier", 
    "Skye Terrier", "Sloughi", "Soft-Coated Wheaten Terrier", "Staffordshire Bull Terrier", 
    "Shetland Sheepdog", "Vizsla", "Weimaraner", "Welsh Corgi", "West Highland White Terrier", 
    "Whippet", "Wire Fox Terrier", "Yorkshire Terrier"
]
